### PR TITLE
Feature/pokedex

### LINKED ISSUE #113: Port pokedex
Port the pokedex from the old pokeclicker

### PR DESCRIPTION
**Pull request by dennism1997**
Create first version of pokedex. I'm not sure which features we want to keep from the old version. This one lists the pokemon with their number when you haven't seen it, and with their number, name and type when you have seen it. It kinda looks like [this](https://www.pokedex.org/)

closes #113

### CODE REVIEW

**Comment by Nyargleblargle** [comment]
The Pokédex doesn't seem to update on capture. The page must be refreshed.

**Comment by dennism1997** [comment]
Think I fixed it! Can you check it out again?

**Comment by Nyargleblargle** [comment]
Yep, everything is working now.

**Comment by Nyargleblargle** [comment]
Pokémon Tower isn't working now

**Comment by dennism1997** [comment]
Yeah but I noticed it on the develop branch too!

**Pull request merged**
