### PR TITLE
Set min height of images

### LINKED ISSUE #333: When catching a Pokémon, the healthbar jumps up for a short time
This is visually very disturbing. It does not happen without catching.

Example:
https://gfycat.com/NextPiercingJaguarundi

### PR DESCRIPTION
**Pull request by RedSparr0w**
Alternative to #334 
Have set the minimum height of the pokeball & pokemon images, this should eliminate the jumping that occours when an image has to be loaded.

closes #333 
closes #334

### CODE REVIEW

**Comment by Ishadijcks** [comment]
Why is this better?

**Comment by Ishadijcks** [comment]
I think you branched from the wrong commit?

I get the following error.

```
TypeError: OakItemRunner.getOakItemByName(...) is undefined
```

**Comment by RedSparr0w** [comment]
Yeah, shouldn't matter, the changes are still the same and won't be affected when merged.

This fixes the jumping issue for when pokemon images need to load, not just pokeballs.
Also does it without adding extra elements, just using styles.

**Comment by Ishadijcks** [comment]
I know, It makes reviewing more of a hassle.

**Comment by RedSparr0w** [comment]
Thanks,

Yeah, i'll update my develop branch :+1:

**Pull request merged**
