### PR TITLE
Apply stricter tslint to all files

### PR DESCRIPTION
**Pull request by dennism1997**

### CODE REVIEW

**Comment by Aegyo** [comment]
Is this supposed to automatically reformat the code?
I'm deliberately doing incorrect whitespace and forgetting semi colons, but I just get this:
```
$ gulp tslint
[13:39:00] Requiring external module babel-register
[13:39:02] Using gulpfile ~/pokeclicker/gulpfile.babel.js
[13:39:02] Starting 'tslint'...

ERROR: ~/pokeclicker/src/scripts/safari/SafariBattle.ts[211, 30]: missing whitespace

[13:39:03] 'tslint' errored after 1.63 s
[13:39:03] Error in plugin "gulp-tslint"
Message:
    Failed to lint: ~/pokeclicker/src/scripts/safari/SafariBattle.ts [211, 30]: missing whitespace.
```
And then I would have to go fix the problem myself.

Also, it only seems to be running tslint when you first start up gulp, it would be nice to run the linter whenever you save as well (like it also refreshes the browser page)

I looked through all of the reformatting changes, and don't see any issue with that.

**Comment by dennism1997** [comment]
You can reformat the code automatically when using webstorm. Webstorm has built in settings to apply tslint. I have changed the gulp file to also run tslint when watching the files 👍

**Comment by Ishadijcks** [comment]
112 changed files? That's gonna create a ton of merge conflicts

**Comment by Ishadijcks** [comment]
@dennism1997 Can you fix these merge conflicts?

**Comment by Ishadijcks** [comment]
I'm gonna close this pr as I decided it's not worth losing the entire `git blame` log for

**Pull request closed without merging**
