### PR TITLE
Closing breeding modal if eggslots are full

### PR DESCRIPTION
**Pull request by Quindon**
QoL change for less clicking

creates egg first, then checks for open eggslots, if there aren't any, modal closes

### CODE REVIEW

**Comment by Aegyo** [comment]
I see you made these changes on your `develop` branch. In the future, I recommend creating a separate branch for your changes, so you can keep your `develop` the same as the main repo. This will be helpful if you ever want to work on a second thing before the first has been merged into the main develop. If you have everything on the same branch, then you won't be able to make pull requests individually.

**Comment by Ishadijcks** [comment]
Looks good, also next time please make an issue first. This way we can confirm that it's something worth working on :)

**Comment by Quindon** [comment]
Thanks for the hit Aegyo, I will try and figure out how to do what you said. 

I didn't want to just show up and make demands, and it seemed like a thing I could acctually do. 
Do you guys prefer just an issue bevor the pr to see if its needed or can both be submitted at the same time?

**Comment by Ishadijcks** [comment]
If you need any help with that, just let us know!

The normal lifecycle would be:
- Submit an issue.
- It gets confirmed as a bug/useful feature/nice improvement, usually with a label or a comment.
- Submit a pull request.
- Get it reviewed and accepted if it properly closes the issue.

This prevents the situation where someone thinks that X should be a feature, while X is not something we want in our game. Think a new feature or a ui change. The above lifecycle can spare the contributor from wasted time if their feature gets rejected before they start working on it.

Of course for small improvements the chance that we want it merged is very high, so there is no real harm in making them at the same time. Just remember that opening an issue first gives us the time to give some feedback or pointers to help you get started.

Hope that explains it!

**Pull request merged**
