### PR TITLE
Cities are grey when locked, and purple when unlocked

### PR DESCRIPTION
**Pull request by dennism1997**
image

### CODE REVIEW

**Comment by Aegyo** [comment]
Is it possible to make unlocked dungeons a different colour to unlocked towns? Maybe check if town name is in dungeonList?

This looks much better already, good job :)

**Comment by dennism1997** [comment]
Then we probably want another color for cleared dungeons too right?

**Comment by Aegyo** [comment]
Yeah, good idea

**Comment by dennism1997** [comment]
image
Something like this? Brown is locked, green is unlocked and blue is cleared

**Comment by Aegyo** [comment]
Looks good to me, I'll give Isha the chance to change any colours though.

**Comment by Ishadijcks** [comment]
Yeah not sure I agree with the colours yet :p

**Comment by BaineGames** [comment]
do we care about players who are colorblind?

**Comment by LetTheDarkRise** [comment]
On Oct 11, 2017 4:31 PM, Isha Dijcks <notifications@github.com> wrote:Maybe if they request it later

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




I know I'm not really an active part of the development, but I am red-green colorblind, and I can't tell the difference between the locked and unlocked dungeons. You might want to make the locked dungeons a dark gray, similar to the locked cities. Adds a nice uniformity, plus I'd know that I can go to the dungeon.

**Comment by Ishadijcks** [comment]
Fair enough!

**Comment by BaineGames** [comment]
well that answers my question then lol

**Comment by dennism1997** [comment]
@LetTheDarkRise How is this?
image

**Comment by LetTheDarkRise** [comment]
That is a lot better, thanks

**Pull request merged**
