### PR TITLE
More achievements (Need help)

### PR DESCRIPTION
**Pull request by tklaxbro**
I made a Statistics.ts file to handle clicks and others. Also created a few more achievements:

- Clicks
- Captures
- Defeats
- Tokens
- Diamonds
- Attack

### CODE REVIEW

**Comment by tklaxbro** [comment]
I am trying to fix the KnockoutObservable not being a proper variable ugh!

**Comment by tklaxbro** [comment]
Because Battle.ts is loading before the Statistics.ts the incrementObservable() is not working for it and all of the others are getting an error like: 
`src/scripts/achievements/ClickRequirement.ts(9,36): error TS2339: Property 'clicks' does not exist on type 'typeof Statistics'.
src/scripts/achievements/ClickRequirement.ts(9,49): error TS2339: Property 'value' does not exist on type 'ClickRequirement'.`

**Comment by dennism1997** [comment]
you should try putting reference paths at the top of your files. For example in the pokemonfactory class:
`///<reference path="PokemonHelper.ts"/>`
`///<reference path="BattlePokemon.ts"/>`
` `
`/**`
` * Created by dennis on 27-06-17.`
` */`
`class PokemonFactory {`
Let me know if it works!

**Comment by Aegyo** [comment]
I realised a lot of these achievements observables will also be useful for creating quests. Since tklaxbro hasn't updated this branch in a while, I'm going to continue from where they left off.
(I'm continuing from the branch you were working on tklaxbro, so everything you have done will still be credited to you when it eventually gets merged)

This pull request can be closed when I push up a branch, but I'll leave it open until then.

**Comment by Aegyo** [comment]
Closing due to new PR #122

**Pull request closed without merging**
