### PR TITLE
Uninterrupting run button

### PR DESCRIPTION
**Pull request by jameswasson**
The run action now cannot interrupt another action and cannot be interrupted. Earlier the run button could have been pressed at any time.

### CODE REVIEW

**Comment by RedSparr0w** [comment]
Did you mean to close this?

**Comment by jameswasson** [comment]
Opps, I didn't. I was trying to undo my last PR from being added to this one, sorry.

**Comment by Ishadijcks** [comment]
I can't reopen it

**Comment by RedSparr0w** [comment]
I believe he has created a new branch and reset his develop branch, so willl need to be a new PR.

**Comment by jameswasson** [comment]
Bummer, I'll make a new one.

**Pull request closed without merging**
