### PR TITLE
Add and implement animated sprites

### PR DESCRIPTION
**Pull request by dennism1997**
All the pokemon you battle (route, dungeon, gym) are now animated with the gen5 sprites!

### CODE REVIEW

**Comment by Aegyo** [comment]
Are there gifs for the shiny versions?

**Comment by dennism1997** [comment]
Not yet :p @Ishadijcks hates animated sprites apparently 😬 
I was thinking of making a settings screen where you can turn them on or off. But currently I'm not sure whether we want them animated or not

**Comment by Ishadijcks** [comment]
Haha yeah I kinda do. Also it's a lot more data we have to load.

**Comment by Ishadijcks** [comment]
Looks semi decent :p

If it's not too much data we can make it a toggle.

**Pull request closed without merging**
