### PR TITLE
Update Dark Mode

### PR DESCRIPTION
**Pull request by RedSparr0w**
**Note:** This is to be merged into the `feature/dark-mode` branch then merged with #329

**Note2:** To review this easier i would suggest hiding whitespace changes:
Screenshot from 2019-06-02 13-34-32

### CODE REVIEW

**Comment by RedSparr0w** [comment]
Fixed dark mode tabs:
Screenshot from 2019-06-02 13-17-04

**Comment by RedSparr0w** [comment]
Make tabs more tab like:
Screenshot from 2019-06-02 13-32-20
Screenshot from 2019-06-02 13-32-56

**Comment by RedSparr0w** [comment]
Update save panel tabs:
Screenshot from 2019-06-02 13-45-45

**Comment by Ishadijcks** [comment]
Please split this pr into changes for the dark theme and the change in the settings menu.

I am not a fan of the changed settings as I didn't use a foreach deliberately so it was possible to customize the UI however we might want later.

I do like the dark theme changes :)

**Comment by RedSparr0w** [comment]
Removed settings panel change, is just the dark mode changes now, if you could re-open.

**Comment by RedSparr0w** [comment]
>I am not a fan of the changed settings as I didn't use a foreach deliberately so it was possible to customize the UI however we might want later.

Although this is no longer a part of this PR, I feel like for now it would be better to have it as the list as it looks a little nicer IMO, until more settings are added?

image

Should I re-open that part as a new PR? or are we fully set on keeping it how it is?

**Pull request merged**
